# playbook CIS
# Kenneth Masis -- > Changed 11/07/2025
# ------------------------------------------------------------------------------
# ------------------------------------------------------------------------------

- name: "CIS | hardening run CentOS"
  hosts: all
  become: true
  vars:
    cis_level_1: true
    cis_level_2: false

  tasks:
  - name: "Apply CIS Hardening for CentOS 7"
    when:
    - ansible_distribution | lower == "centos"
    - ansible_distribution_major_version == "7"
    ansible.builtin.include_role:
      name: ansible-cis-centos7